version: '3.1'

services:
  database:
    image: postgres:latest
    container_name: database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=user_management_application_db

  auth-server:
    image: spring-6-auth-server:latest
    container_name: auth-server
    ports:
      - "9000:9000"

  application:
    image: user-management-api:latest
    container_name: application
    ports:
      - "8080:8080"