version: '3.1'

services:
  database:
    image: postgres:latest
    container_name: database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=team_sphere_db

  application:
    image: team-sphere-backend:latest
    container_name: application
    ports:
      - "8080:8080"