server:
  port: 8080
spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/team_sphere_db

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true

  flyway:
    baseline-on-migrate: true
    enabled: true
    user: postgres
    password: root
    baseline-description: "init"
    baseline-version: 1

  sql:
    init:
      mode: always