server:
  port: 8080
spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/team_sphere_db

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yml
    da


  sql:
    init:
      mode: always