server:
  port: 8080
  address: 0.0.0.0

spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/team_sphere_db

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true

  sql:
    init:
      mode: always

jwt:
  secret: ${SECRET_KEY}
  expiration-time: 7d