server:
  port: 8080
  address: 0.0.0.0

spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_CONNECTION_URL}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true

#  sql:
#    init:
#      mode: always # UNCOMMENT IF YOU NEED TO AUTO SEED SOME SAMPLES OF DATA

jwt:
  secret: ${SECRET_KEY}
  expiration-time: 7d